# ----------------INMUEBLES---------------------

# GET http://localhost:3030/inmuebles HTTP/1.1
# content-type: application/json

# POST http://localhost:3030/inmuebles HTTP/1.1
# content-type: application/json

# {
#       "ambientes": "no lo se",
#       "rangoMin": "1000000",
#       "rangoMax": "5000000",
#       "mtCuadrado": "90", 
#       "corredor": "no lo se",
#       "ubicacion": "coyoacan",
#       "imagen": "imagen",
#       "descripcion": "otro inmueble",
#       "nDormitorio": 8,
#       "nBano": 4,
#       "tipoPropiedad": "mansion",
#       "estado": "bueno"
# }


# ----------------USUARIO---------------------

# GET http://localhost:3030/usuario/obtener HTTP/1.1
# content-type: application/json

# POST http://localhost:3030/usuario/guardar HTTP/1.1
# content-type: application/json

# {
#   "nombre": "prueb2a",
#   "apellido_p": "prueba2",
#   "apellido_m": "prueba2",
#   "correo": "prueb2a",
#   "contrasena": "prueba2"
# }

# POST http://localhost:3030/usuario/modificar HTTP/1.1
# content-type: application/json

# {
#   "idusuario": 3,
#   "nombre": "modificado",
#   "apellido_p": "prueba2",
#   "apellido_m": "prueba2",
#   "correo": "prueb2a",
#   "contrasena": "prueba2"
# }

# DELETE  http://localhost:3030/usuario/eliminar HTTP/1.1
# content-type: application/json

# {
#   "idusuario": 1
# }





# await sequelize.sync();